data:
  root: '/home/redwan/Desktop/MashukBhai/InferenceFusionPaper2020/dataset/caltech/analysis/SDS-RCNN/SDS-RCNN'
  folders:
    - set06
    - set07
    - set08
    - set09
    - set10
dirs:
  video: "/home/redwan/Desktop/MashukBhai/InferenceFusionPaper2020/dataset/caltech/analysis/{}/{}.seq"
  annotation: "/home/redwan/Desktop/MashukBhai/InferenceFusionPaper2020/dataset/caltech/data/annotations/{}/{}.vbb"
  output: "results"